#!/usr/bin/env python3

"""Module used to manage the Application Settings.

At startup, the application generate an AppSettings object which is a singleton. At startup,
this object is generated after reading env files. During Runtime, the application (Flask or
the async runner) check this object to get settings of the application

Example:
    from lolapy.tools import settings
    my_settings = settings.get()
    my_settings.lolapy_host_ip
"""

from __future__ import annotations
from enum import Enum
from pathlib import Path
import os
import sys
import re
from typing import ClassVar
import logging

from pydantic import BaseModel, validator, ValidationError

from lolapy.tools import errors as tools_errors


class LogLevel(Enum):
    debug = "DEBUG"
    production = "PRODUCTION"


class AppSettings(BaseModel):
    """Settings of the whole application.

    This structure act like a Singleton. The class itself is stored in the _instance_ class variable.
    During the build step, we must check if _instance_ is 'None' and if yes, parse env file and generate structure
    and if no, just return the _instance_ value.
    Attributes:
        _instance_: AppSettings | None: Class-Variable where to store the self-reference of the object

        frontend_api_ip: str: Adresse ip or url of the frontend web application
        frontend_api_port: int: Port of the frontend web application
        frontend_api_log_url: str: Url where to send logs to the frontend
        frontend_api_fake: bool: If set to True, no request will be send to the frontend
            the "frontend" will respond 200 everytimes
        frontend_api_prepare_result_complete_url: str: Usually "/api/scenario/results/complete"
        frontend_api_prepare_result_error_url: str: Usually "/api/scenario/results/error"
        lolapy_host_ip: str: IP to use for Lolapy Backend
        lolapy_host_port: int: Port to use for Lolapy Backend
        lolapy_async_queue_file: Path: Path where to store the sqlite async file
        lolapy_log_file: Path: Path where to store logs of the Backend service
        lolapy_log_level: LogLevel: could be "debug" or "production"
            "debug" environment: Enable logs for DEBUG/INFO level
            "production" environment: Disable logs for DEBUG/INFO level
        lolapy_dataset_decrypt_key: Path: Full Path of the key used to decrypt encrypted dataset
        lolapy_dataset_path: Path: Path where dataset are stored. This directory should be a NFS mouting point
            between sftp server and the backend
        lolapy_disable_frontend_logs: bool: Disable logs to the fronted (on AppSettings.frontend_api_log_url)
            It does not disable logs from nextflow.
        sql_host_ip: str: IP or url of the sql server
        sql_host_port: int: Port of the sql server
        sql_root_user: str: Root user of the sql server
        sql_root_password: str: Root password of the sql server
        nextflow_executable: Path: Full path of the nextflow binary
        nextflow_log_listener_host: str: Url of the nextflow log listener
            (usually http://${LOLAPY_HOST_IP}:${LOLAPY_HOST_PORT}/nf_logs)
        nextflow_workdir: Path: Directory where to store data generated by nextflow (temporary data,
            results, template, ...). This directory should be a NFS mouting point between the
            computing cluster and the backend
        nextflow_scenario_dir: Path: Directory where to store data generated by nextflow (temporary data,
            results, template, ...). This directory should be a NFS mouting point between the
            computing cluster and the backend
        nextflow_algorithm_dir: Path: Directory where to store data generated by nextflow (temporary data,
            results, template, ...). This directory should be a NFS mouting point between the
            computing cluster and the backend
        harbor_host: str: IP or URL of the harbor server
        harbor_user: str | None: User to use for authentication to the harbor. If empty, disable
            authentication to the harbor server
        harbor_password: str | None: Password to use for authentication to the harbor server. If empty,
            disable authentication to the harbor server.
        harbor_pull_images: bool: If set to True, pull image to the harbor. If no, use only local images.
        cluster_type: str: type of the cluster. Could be "local", "slurm" or "k8s".
            "local": run on the local machine
            "slurm": run on a slurm cluster
            "k8s": run on a kubernetes cluster
        k8s_pvc_name: str | None: Name of the PVC to use for storage in k8s mode.
        k8s_mount_path: str: Path where to mount the PVC in k8s pods.
        k8s_namespace: str: Namespace to use in k8s cluster.
        k8s_service_account: str: Service account to use in k8s cluster.
        http_proxy: str | None: Default to None. If the backend should use a proxy to download ressources on internet (git repositories for example)
    """

    _instance_: ClassVar[AppSettings] | ClassVar[None] = None
    frontend_api_ip: str
    frontend_api_port: int
    frontend_api_log_url: str
    frontend_api_fake: bool = False
    frontend_api_prepare_result_complete_url: str
    frontend_api_prepare_result_error_url: str
    lolapy_host_ip: str
    lolapy_host_port: int
    lolapy_async_queue_file: Path
    lolapy_log_file: Path
    lolapy_log_level: LogLevel
    lolapy_dataset_decrypt_key: Path
    lolapy_dataset_path: Path
    lolapy_disable_frontend_logs: bool
    # trax_check_images: bool
    # trax_image_client: str
    # trax_image_admin: str
    # sql_host_ip: str
    # sql_host_port: int
    # sql_root_user: str
    # sql_root_password: str
    nextflow_executable: Path
    nextflow_log_listener_host: str
    nextflow_workdir: Path
    nextflow_scenario_dir: Path
    nextflow_algorithm_dir: Path
    harbor_host: str
    harbor_user: str | None = None
    harbor_password: str | None = None
    harbor_pull_images: bool
    cluster_host: str
    cluster_type: str = "local"
    k8s_pvc_name: str | None = None
    k8s_mount_path: str = "/home/lolauser/nf-workdir"
    k8s_namespace: str = "default"
    k8s_service_account: str = "default"
    http_proxy: str | None = None

    @validator("http_proxy")
    def validate_http_proxy(cls, value) -> str | None:
        if value:
            return value
        else:
            return None

    def print(self):
        from pprint import pprint

        pprint(self.dict())


class AppSettingsBuilder:
    def __init__(self):
        self.env_file = self._check_env_file()

    def build(self) -> "AppSettings":
        """Create or return the AppSettings object.

        This method return the Singleton of [AppSettings].
        It builds the [AppSettings] after parsing the env file.
        Returns:
            AppSettings:
        """
        variables = self._read_file()
        expanded_variables = self.__expand_variables(variables)
        try:
            new_settings = AppSettings(**expanded_variables)
        except ValidationError as pydantic_error:
            raise tools_errors.SettingsMissingParameters(
                env_file=os.environ["ENV_FILE"], validation_error=pydantic_error
            )
        AppSettings._instance_ = new_settings
        return new_settings

    @staticmethod
    def reset():
        AppSettings._instance_ = None

    def _check_env_file(self) -> Path:
        """Check the variable and the path of the env file.

        Stop the program if:
          - the variable is not set
          - the file does not exist
        Returns:
            Path: Full path of the environment file
        """
        var_file = "ENV_FILE"

        if var_file not in os.environ:
            msg = (
                f"No '{var_file}' set.\n"
                "Please set an environment file before starting Lolapy.\n"
                "For example, use:\n"
                f"  export {var_file}=/full_path_to_en_file"
            )
            print_stderr(msg)
            sys.exit(1)

        env_file = Path(os.environ[var_file])
        if not env_file.exists():
            msg = f"Env file '{str(env_file)}' set in '{var_file}' variable does not exist"
            print_stderr(msg)
            sys.exit(1)

        return env_file

    def _read_file(self) -> dict:
        """Read env file(s) and extract variables.

        Args:
            s: Variable containing the env file
        Returns:
            A dictionnary containing all env variables
        Raises:
            lolapy.tools.errors.EnvFileError: if there are errors when reading the file
        """
        # split env file with colon (as PATH in bash)
        env_vars = {}
        try:
            with open(self.env_file) as i_buffer:
                for line in i_buffer:
                    if (
                        line.startswith("#")  # remove line with commentaries
                        or not line.strip()  # remove empty lines
                        or line.startswith(" ")  # remove blank lines (with spaces)
                    ):
                        continue
                    key, value = line.strip().split("=", 1)
                    key = key.strip('"')  # remove first and last " char
                    value = value.strip('"')  # remove first and last " char
                    if key in env_vars:
                        logging.warning(f"Variable '{key}' set in different files")
                    env_vars[key] = value
        except (OSError, ValueError) as e:
            raise tools_errors.EnvFileError(env_file=str(self.env_file), stderr=str(e))

        return env_vars

    def __expand_variables(self, env_var: dict):
        """Search for bash variables in all envs and expand them.

        variables must be in Bash format with '$' and surrounded by '{}' like MY_FILE=${ROOT}/my_file.txt
        Args:
            env_var: Dictionnary to edit in-place containing all env variables and them to expand.
        Note:
            Does not raise an error if the variable is not available. Just raise a warning.
        """
        ## Match text between '${' and '}'
        bash_regex = re.compile(r"(\${([a-zA-Z0-9_]+)})")

        # is True when a variable was expand in the loop. It can expand futures variables after multiple loop
        did_expand = True
        while did_expand:
            did_expand = False
            for var in env_var:
                if match := bash_regex.search(env_var[var]):
                    # match.group(1) looks like '${VAR_NAME}' and match.group(2) like 'VAR_NAME'
                    # Search for exact variable name if it exists. If not, it should exists after a full for loop
                    if match.group(2) in env_var:
                        # Expand the variable
                        env_var[var] = env_var[var].replace(
                            match.group(1), env_var[match.group(2)]
                        )
                        did_expand = True

        # Check if some env_variables still have expansion to do
        # Send a warning if yes
        for var in env_var:
            if bash_regex.search(env_var[var]):
                logging.warning(
                    f"Env variable '{var}' cannot be expand. Value = '{env_var[var]}'."
                )

        # lower all variables to match fields in AppSettings
        lower_variables = {}
        for key, value in env_var.items():
            lower_variables[key.lower()] = value

        return lower_variables

    @staticmethod
    def build_default():
        """Build a "default" settings. Used only for tests and other library.

        This method can be used to avoid setting a ENV_FILE. It set all variable to their default value.
        BE CAREFUL with this method. It could break things
        """
        my_app_settings = AppSettings(
            _instance_ = None,
            frontend_api_ip = "",
            frontend_api_port = 0,
            frontend_api_log_url = "",
            frontend_api_fake = False,
            frontend_api_prepare_result_complete_url = "",
            frontend_api_prepare_result_error_url = "",
            lolapy_host_ip = "",
            lolapy_host_port = 0,
            lolapy_async_queue_file = Path(""),
            lolapy_log_file = Path(""),
            lolapy_log_level = LogLevel.debug,
            lolapy_dataset_decrypt_key = Path(""),
            lolapy_dataset_path = Path(""),
            lolapy_disable_frontend_logs = False,
            # trax_check_images=False,
            # trax_image_client="trax_client",
            # trax_image_admin="trax_admin",
            # sql_host_ip = "",
            # sql_host_port = 0,
            # sql_root_user = "",
            # sql_root_password = "",
            nextflow_executable = Path(""),
            nextflow_log_listener_host = "",
            nextflow_workdir = Path(""),
            nextflow_scenario_dir = Path(""),
            nextflow_algorithm_dir = Path(""),
            harbor_host = "",
            harbor_user = None,
            harbor_password = None,
            harbor_pull_images = False,
            cluster_host = "",
            cluster_type = "local",
            k8s_pvc_name = None,
            k8s_mount_path = "/home/lolauser/nf-workdir",
            k8s_namespace = "default",
            k8s_service_account = "default",
            http_proxy = None)
        AppSettings._instance_ = my_app_settings


def get() -> "AppSettings":
    """This function return an instance of AppSettings.

    If the the singleton is set, return directly AppSettings, else,
    build and return an AppSettings instance.
    """
    if AppSettings._instance_ is None:
        return AppSettingsBuilder().build()
    return AppSettings._instance_


def print_stderr(msg: str):
    """Print `msg` to stderr.

    Edit `msg` and add a red 'ERROR: ' at the beginning of each lines

    Args:
        msg: Message to print in the stderr
    """
    lines = []
    for line in msg.split("\n"):
        lines.append(f"\033[91mERROR: \033[0m{line}")
    msg = "\n".join(lines)
    print(msg, file=sys.stderr)


class EditSettings:
    """Create a context manager to edit env variables for tests.

    Examples:
        >>> with EditEnvironment:
        >>>     settings.get().http_proxy = "https://8.8.8.8"
        >>>     #do_stuff ....
    # Here HTTP_PROXY is back to normal
    """

    def __init__(self):
        self.settings = get()
        self.settings_backup = self.settings.copy()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.settings = self.settings_backup
        AppSettings._instance_ = self.settings_backup
