services:
  # In Case you need phpmyadmin, uncomment the following lines:
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     APACHE_HTTP_PORT_NUMBER: 9010
  #     PMA_HOST: ${PMA_HOST}
  #     PMA_PORT: 3306
  #     TZ: Europe/Paris
  #   command: /bin/bash -c "sed -i \"s/80/$$APACHE_HTTP_PORT_NUMBER/g\" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"
  #   restart: ${RESTART_SERVICES:-no}

  app:
    image: frontend
    build:
      context: '.'
    volumes:
      - .env:/var/www/html/.env
    environment:
      TZ: Europe/Paris
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: ${RESTART_SERVICES:-no}
    ports:
      - 8080:80

  sftp:
    image: atmoz/sftp
    volumes:
      - sftp_data:/home/${SFTP_USER}/upload
    ports:
      - ${SFTP_PORT}:22
    command:
      - ${SFTP_USER}:${SFTP_PASSWORD}:1001

volumes:
  sftp_data: 

