- name: Clone Git repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"
    version: fix/devops
    force: yes
    
- name: Copy environment variables file
  copy:
    src: "{{ git_repo_dest }}/.env.sample"
    dest: "{{ git_repo_dest }}/.env"
    remote_src: yes

- name: Set environment variables
  lineinfile:
    path: "{{ git_repo_dest }}/.env"
    regexp: '^{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'LOLAPY_API_ADRESS', value: '{{ arch_ip }}' }
    - { key: 'ENABLE_API_ACCESS_CONTROL', value: 'true' }
    - { key: 'MYSQL_HOST', value: 'db' }
    - { key: 'ROOT_DIR', value: '{{ git_repo_dest }}' }

- name: Copy environment variables file
  copy:
    src: "{{ git_repo_dest }}/.env"
    dest: "{{ git_repo_dest }}/build/app/.env"
    remote_src: yes
    
- name: Start application with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ git_repo_dest }}"
    state: present
  register: compose_output

- name: Pause for 1 minute for database to start
  ansible.builtin.pause:
    seconds: 60

- name: Run database fixture command
  command: "{{ app_fixture_command }}"
  args:
    chdir: "{{ git_repo_dest }}"

- name: prepare sftp container
  command: "docker exec frontend-sftp-1 chown {{ dmz_sftp_user }} /home/{{ dmz_sftp_user }}/upload"  