services:
  backend:
    image: backend
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - ENV_FILE=/app/.env
    volumes:
      - .env:/app/.env
      - lolasqlite:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/tmp/certs
      - /home/lolauser:/home/lolauser 
    command: 
      - ./venv/bin/python
      - -m
      - lolapy.bin.app
  hueyconsumer:
    image: backend
    hostname: hueyconsumer
    build:
      context: .
    environment:
      - ENV_FILE=/app/.env
    network_mode: host
    privileged: true
    group_add: 
      - ${DOCKER_GROUP}
    user: lolauser
    volumes:
      - .env:/app/.env
      - lolasqlite:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - ./certs/:/tmp/certs
      - /etc/munge/munge.key:/etc/munge/munge.key
      - /etc/slurm/slurm.conf:/etc/slurm/slurm.conf
      - /home/lolauser:/home/lolauser
      - /var/run/munge:/var/run/munge:ro
      - /etc/munge:/etc/munge:ro
    command:
      - "venv/bin/huey_consumer"
      - "lolapy.bin.async_tasks.huey"
      - "-w 1"
  sftp:
    image: atmoz/sftp
    volumes: 
      - /home/lolauser/nf-workdir/datasets:/home/aziz/upload
    ports:
      - 2222:22
    command:
      - aziz:password:1001


networks: 
  frontend_default: 
    external: true
     
volumes: 
  lolasqlite: 
  scenarios_data:
  ssh_data:
