#!/usr/bin/env python3

from pathlib import Path
import os

import pytest

from sandbox.run import check_docker
from sandbox import errors

GOOD_SCRIPT = """#!/bin/bash
echo 'Docker version 20.10.01, build '"""
GOOD_SCRIPT_BIS = """#!/bin/bash
echo 'Docker version 20.10.01, build '"""

SCRIPT_WITH_WRONG_VERSION = """#!/bin/bash
echo 'Docker version 19.05.07, build '"""

@pytest.fixture(scope="function")
def fixture_create_fake_docker(tmp_path, script_content) -> Path:
    """Create a fake docker script and return the path of the dir where the script is stored.

    Args:
        tmp_path: Path: Fixture generated by pytest that create a temp directory
        script_content: str: Content of the script to write in the script
    Returns:
        Path: Return the path of the directory where the script is stored.
    """
    directory = tmp_path / "sub"
    directory.mkdir()
    docker_script = directory / "docker"
    docker_script.write_text(script_content)
    docker_script.chmod(0o700)
    return directory

@pytest.mark.parametrize('script_content', [GOOD_SCRIPT])
def test_docker_good(fixture_create_fake_docker):
    """Test if the function can find a 'real' docker program"""
    os.environ["PATH"] = str(fixture_create_fake_docker)
    check_docker()

@pytest.mark.parametrize('script_content', [GOOD_SCRIPT_BIS])
def test_docker_good_bis(fixture_create_fake_docker):
    """Test if the function can find a 'real' docker program"""
    os.environ["PATH"] = str(fixture_create_fake_docker)
    check_docker()

@pytest.mark.parametrize('script_content', [SCRIPT_WITH_WRONG_VERSION])
def test_docker_wrong_version(fixture_create_fake_docker):
    """Test if the function raise error if docker have wrong version"""
    os.environ["PATH"] = str(fixture_create_fake_docker)
    with pytest.raises(errors.RequirementsError):
        check_docker()
