git_repo_url: ""
git_repo_dest: "/opt/lola/lolapy"
harbor_version: "2.13.3"
nfs_allowed_network: "*"
lolauser_password: ""
cron_script_name: "sftp.sh"
cron_job_name: "SFTP Sync"
cron_minute: "*"
cron_hour: "*"
cron_day: "*"
cron_month: "*"
cron_weekday: "*"
arch_ip: ""
harbor_hostname: ""
harbor_password: ""
nfs_user: "lolauser"
nfs_export_path: "/home/lolauser/nf-workdir"
slurm_role: "client"
dmz_ip: ""
dmz_sftp_user: ""
dmz_sftp_password: ""
dmz_sftp_port: "2222"
arch_sftp_user: ""
arch_sftp_password: ""
arch_sftp_port: "2222"
slurm_cluster_name: "cluster-lola"
harbor_ssl: false