#!/usr/bin/env python3

import pytest
from lolapy.blueprints.dataset import GetDatasetJSON

from lolapy.tools.errors import LolapyGlobalError
from lolapy.tools import settings

## Tests for request to remove dataset
## 1. Could not connect to the database       -> MySQLError()              -> HTTP 500
## 2. Dataset permission denied               -> DatasetPermissionDenied() -> HTTP 403
## 3. Database does not exist                 -> DatasetDoesNotExist()     -> HTTP 404
## 4. Unexpected error when removing database -> Exception                 -> HTTP 500
## 5. Success                                 -> no exception              -> HTTP 200

@pytest.mark.integration
def test_route_dataset_remove_connection_error(flask_client):
    """Test for a missing connection to a database"""
    with settings.EditSettings():
        settings.get().sql_host_ip = "192.168.0.255" # Set a random fake ip adress that cannot match to anything
        settings.get().sql_host_port = 99999         # and a random port in case sql server is on 0.0.0.0
        settings.get().frontend_api_fake = True      # Checking permission on dataset is the first step
                                                     # so disable checking
        response = flask_client.post("/dataset/remove", json={"user": "_", "dataset": "_"})
        assert response.status_code == 500
        assert response.data == bytes(LolapyGlobalError.standard_public_message, "utf_8")


@pytest.mark.integration
def test_route_dataset_remove_permission_denied(flask_client):
    """Test if the request raise à 403 (permission denied) when user have no access on the dataset.
    """
    response = flask_client.post("/dataset/remove", json={"user": "_", "dataset": "_"})
    assert response.status_code == 403

@pytest.mark.integration
def test_route_dataset_remove_database_does_not_exist(flask_client):
    """Test if the route return the correct message if database does not exist.

    The dataset must exist on the frontend side, BUT not on the backend side. i.e. the sql server
    does not contain the dataset
    TODO: Edit this. For tests purpose, we must add a dataset in the frontend but no dataset in the backend
          Do this with ansible
    """
    # response = flask_client.post("/dataset/remove", json={"user": "_", "dataset": "_"})
    # assert response.status_code == 403
    pass

@pytest.mark.integration
def test_route_dataset_remove_success(flask_client):
    """Test if the route can really remove the database.

    TODO: Make a backup of the database before and restore it after
    Note:
        The user_hash and dataset_hash must match the ones generated by ansible fixtures during installation
    """
    json_data = GetDatasetJSON(dataset="D51661bf637581680c38e5bd5ae485b231d4c5555", user="U3c33ad8b92e9b1455d87605e7343582889d13d39")

    response = flask_client.post("/dataset/remove", json=json_data.dict())
    assert response.status_code == 200
