- name: Configure ARCH servers
  hosts: arch
  become: yes
  
  roles:
    - common
    - docker
    - create_user
    - cron_script
    - harbor
    - nfs_server
    - { role: slurm_client, when: orchestrator | default('slurm') == 'slurm' }
    - lolapy
