- name: Gather facts from all hosts
  gather_facts: yes
  hosts: all
# - name: Global Setup (All Nodes)
#   hosts: all
#   become: yes
#   roles:
#     - common
#     - docker
#     - create_user

- name: Setup Calc Master Node (Slurm Controller, Kubernetes Control Plane)
  hosts: calc_master
  become: yes
  roles:
    - { role: kubernetes_control_plane, when: setup_kubernetes | default(false) | bool }
    - { role: slurm_controller, when: orchestrator | default('slurm') == 'slurm' }

# - name: Setup Arch Node (Slurm Client, NFS, Harbor, Lolapy)
#   hosts: arch
#   become: yes
#   roles:
#     - { role: slurm_client, when: orchestrator | default('slurm') == 'slurm' }
#     - nfs_server
#     - harbor
#     - cron_script
#     - lolapy

# - name: Setup DMZ Services (Harbor, Frontend)
#   hosts: dmz
#   become: yes
#   roles:
#     - harbor
#     - frontend

- name: Finish Calc Workers Setup (NFS Client, Workers, SSH Keys, Kubernetes Workers)
  hosts: calc_worker
  become: yes
  roles:
    - { role: kubernetes_worker, when: setup_kubernetes | default(false) | bool }
    - { role: nfs_client, when: orchestrator | default('slurm') == 'slurm' }
    - { role: slurm_worker, when: orchestrator | default('slurm') == 'slurm' }
    - { role: ssh_key, when: orchestrator | default('slurm') == 'slurm' }
