#!/usr/bin/env python3

"""Module used to sanitize errors raised by the pydantic library during config file parsing.

When there are missing field in json file or error in the json file, pydantic raises errors.
This module parses the error and generates a proper error message.
"""

from __future__ import annotations
import logging
from pathlib import Path

import pydantic

class ImplementError(Exception):
    def __init__(self, message: str):
        self.message = message
    def __str__(self):
        return self.message
    def __repr__(self):
        return self.message

class SanitizePydanticError:
    """Sanitize missing field or field error when reading file"""
    def __init__(self, filename: Path, pydantic_error: pydantic.ValidationError):
        self.filename: Path = filename
        self.pydantic_error: pydantic.ValidationError = pydantic_error
        self.sanitized_message: str|None = None  # Set-up in sanitize()

    def _gen_path_field(self, loc: tuple[str]) -> str:
        """Transform the name of the field of pydantic into a string.

        In pydantic, loc can have different forms like:
        - ("name", ) tranformed into "'name'"
        - ("parameters", 0, "name"), transformed into "in the 'parameters', element 0, field 'name'"
        Args:
            loc: tuple of string containing the Path of the error. Generated by pydantic.
        Returns:
            The error message formatted. See below for example
        """
        if len(loc) == 1:
            return f"'{loc[0]}'"

        full_text = "in the nested: "
        between_field = ", "
        for ii in loc:
            if isinstance(ii, str):
                full_text += f"field '{ii}'{between_field}"
            elif isinstance(ii, int):
                full_text += f"element '{ii}'{between_field}"
            else:
                full_text += f"'{ii}'{between_field}"
        # Remove last part of the string. like ', '
        full_text = full_text.strip(between_field)
        return full_text

    def sanitize(self) -> Self:
        """Generate the real error message based on the pydantic error.

        Set-up self.sanitized_message
        """
        try:
            for error in self.pydantic_error.errors():
                error_message = ""
                loc = self._gen_path_field(error['loc'])
                if "type_error" in error["type"] or "value_error" in error["type"]:
                    error_message = f"Error {loc}: {error['msg']}"
                elif "missing" in error["type"]:
                    error_message = f"Missing: {loc}: {error['msg']}"
                self.sanitized_message = error_message
        except Exception as e:
            raise ImplementError(str(e))
        return self

    def log(self):
        """Log the error message to the error logging system.

        Does not do anything else.
        """
        logging.error(self.sanitized_message)
