all:
  vars:
    ansible_user: ubuntu
    # If a bastion host is required for SSH access, uncomment and configure the ProxyJump line below:
    # ansible_ssh_common_args: >
    #   -o ProxyJump=bastion-user@bastion-host
  children:

    dmz:
      hosts:
        dmz-server-1:
          ansible_host: 10.0.0.1 # Replace with your DMZ IP
          ansible_user: ubuntu # Replace with your DMZ user

    arch:
      hosts:
        arch-server-1:
          ansible_host: 10.0.1.1 # Replace with your Arch IP
          ansible_user: ubuntu # Replace with your Arch user
          
    calc:
      hosts:
        calc-server-1:
          ansible_host: 10.0.2.1 # Replace with your Calc IP
          ansible_user: ubuntu # Replace with your Calc user