all:
  vars:
    # If a bastion host is required for SSH access, uncomment and configure the ProxyJump line below:
    #ansible_ssh_common_args: -o ProxyJump=bastion-server
  children:

    dmz:
      hosts:
        dmz-server-1:
          ansible_host: 10.0.0.13 # Replace with your DMZ IP
          ansible_user: ubuntu # Replace with your DMZ user

    arch:
      hosts:
        arch-server-1:
          ansible_host: 10.0.1.1 # Replace with your Arch IP
          ansible_user: ubuntu # Replace with your Arch user

    calc:
      children:
        calc_master:
        calc_worker:

    calc_master:
      hosts:
        calc-master-1:
          ansible_host: 10.0.2.0 # Replace with your Calc Master IP
          ansible_user: ubuntu # Replace with your Calc Master user

    calc_worker:
      hosts:
        calc-worker-1:
          ansible_host: 10.0.2.1 # Replace with your Calc Worker IP
          ansible_user: ubuntu # Replace with your Calc Worker user

    workers:
      children:
        calc_worker: