#!/usr/bin/env python3

"""Handle errors generated by incoming request (other -> backend)"""

from __future__ import annotations
import flask

import pydantic

from lolapy.errors import LolapyGlobalError


class BadRequestFormat(LolapyGlobalError):
    def __init__(self, public_message: str, message: str):
        self.public_message = public_message
        self.message = message

    @classmethod
    def from_ValidationError(cls, request: flask.Request, error: pydantic.ValidationError) -> BadRequestFormat:
        errors = []
        for err in error.errors():
            loc = " -> ".join(str(l) for l in err["loc"])
            msg = err["msg"]
            errors.append(f"'{loc}': {msg}")

        message = f"Error with request '{request}': {', '.join(errors)}"
        public_message = f"Error in request: {', '.join(errors)}"
        return cls(public_message=public_message, message=message)
