#!/usr/bin/env python3

"""Handle errors generated by incoming request (other -> backend)"""

from __future__ import annotations
import flask

import pydantic

from lolapy.errors import LolapyGlobalError


class BadRequestFormat(LolapyGlobalError):
    def __init__(self, public_message: str, message: str):
        self.public_message = public_message
        self.message = message

    @classmethod
    def from_ValidationError(cls, request: flask.Request, error: pydantic.ValidationError) -> BadRequestFormat:
        missing_fields = [str(field["loc"][0]) for field in error.errors()]
        message = f"Error with request '{request}': Missing field(s): '{', '.join(missing_fields)}'"
        public_message = f"Error in request: Missing field(s): '{', '.join(missing_fields)}'"
        return cls(public_message=public_message, message=message)
