#!/usr/bin/env python3

import os
import random
import logging

from src import utils
from src import env
from src import docker


class CONST:
    script_name = os.path.basename(__file__)


def start_trax(env: env.Env, container_name, db, writable=False):
    if writable:
        docker_image = env.get("DOCKER_TRAX_ADMIN_NAME")
    else:
        docker_image = env.get("DOCKER_TRAX_CLIENT_NAME")

    my_trax_server = docker.Compose(
        name=container_name,
        image=docker_image,
        env_variables={"DB_DATABASE": db},
    )
    my_trax_server.add_volume(env.get("TRAX_ENV"), "/var/www/html/traxlrs/.env")
    my_trax_server.run_compose()


def stop_trax(container_name):
    """
    Stop the running trax container based on the name of the container
    """
    my_container = docker.Compose(
        name=container_name,
    )
    my_container.stop()


def gen_admin(container_name):
    """
    generate a Admin user/password for a running trax container
    """
    my_container = docker.Docker(
        name=container_name,
        cmd="php /var/www/html/traxlrs/artisan user:create-admin",
    )
    my_container.exec()


if __name__ == "__main__":
    import sys
    import argparse

    log_id = random.randrange(100_000)
    logging.basicConfig(
        level=logging.INFO,
        format=f"%(asctime)s:{CONST.script_name}:ID{log_id}:%(levelname)s: %(message)s",
        datefmt="%m/%d/%Y %I:%M:%S %p",
    )

    parser = argparse.ArgumentParser(
        description="Manage Trax Containers", add_help=False
    )
    parser.add_argument(
        "-h", "--help", action=utils._HelpAction, help="show this help message and exit"
    )

    create_parsers = parser.add_subparsers(help="sub-command help")

    # Create the parser for the "create" command
    parser_create = create_parsers.add_parser("start", help="Create a trax container")
    parser_create.set_defaults(command="start")
    parser_create.add_argument(
        "-d", "--db", required=True, help="Database to bind in the container"
    )
    parser_create.add_argument(
        "-e", "--env", required=True, help="Path to the .env file"
    )
    parser_create.add_argument(
        "-p",
        "--port",
        help="Port to used to bind the service on localhost. (Optionnal. The script can find a available one in the range 8080-8180)",
    )
    parser_create.add_argument("--name", required=True, help="Name of the container")
    parser_create.add_argument(
        "--writable",
        action="store_true",
        help="Enable the create of admin, populate database or log into the web interface (Optionnal)",
    )

    # Create the parser for the "stop" command
    parser_stop = create_parsers.add_parser("stop", help="Stop the container")
    parser_stop.set_defaults(command="stop")
    parser_stop.add_argument("-e", "--env", required=True, help="Path to the .env file")
    parser_stop.add_argument("--name", required=True, help="Name of the container")

    # Create the parser for the "gen_admin" command
    parser_gen_admin = create_parsers.add_parser(
        "gen_admin", help="Generate an Admin user for the container"
    )
    parser_gen_admin.set_defaults(command="gen_admin")
    parser_gen_admin.add_argument("--name", required=True, help="Name of the container")
    parser_gen_admin.add_argument(
        "-e", "--env", required=True, help="Path to the .env file"
    )

    # If no argument provided, print --help
    if len(sys.argv) == 1:
        parser.print_help(sys.stdout)
        sys.exit(0)

    args = parser.parse_args()

    # Read the env file
    env = env.Env(args.env)

    if args.command == "start":
        start_trax(env, container_name=args.name, db=args.db, writable=args.writable)
    elif args.command == "stop":
        stop_trax(args.name)
    elif args.command == "gen_admin":
        gen_admin(args.name)
    else:
        # unreachable
        exit(0)
