#!/usr/bin/env python3

import os
import random
import logging

from src import env, docker
from src import error, warning
from src import utils


class CONST:
    script_name = os.path.basename(__file__)


def populate_db(env: env.Env, db: str, json: str):
    json = os.path.abspath(json)
    utils.is_file_readable(json)
    container_name = f"trax_{db}_{random.randrange(10_000)}"

    my_trax_server = docker.Compose(
        name=container_name,
        env_variables={"DB_DATABASE": db},
        image=env.get("DOCKER_TRAX_ADMIN_NAME")
    )
    my_trax_server.add_volume(json, "/xapi.json")
    my_trax_server.add_volume(env.get("TRAX_ENV"), "/var/www/html/traxlrs/.env")
    my_trax_server.run_compose()

    dock_create_client = docker.Docker(
        command="php /var/www/html/traxlrs/artisan client:create",
        name=container_name,
    )
    dock_create_client.exec_docker()

    dock_populate = docker.Docker(
        name=container_name,
        command="curl --location \
--request POST 'localhost:80/trax/ws/xapi/statements' \
--header 'X-Experience-API-Version: 1.0.3' --header 'Accept: application/json' \
--header 'Authorization: Basic dGVzdHN1aXRlOnBhc3N3b3Jk' \
--header 'Content-Type: application/json' -d '@/xapi.json'"
    )
    dock_populate.exec_docker()

    my_trax_server.stop()
    exit(0)


def execute_mysql_cmd(env, cmd):
    logging.info("mySQL command START")

    container_name = env.get("COMPOSE_DB_NAME")
    my_container = docker.Docker(
        name=container_name,
        command=f"/usr/bin/mysql -u{env.get('MYSQL_ROOT_PASSWORD')} --password={env.get('MYSQL_ROOT_PASSWORD')} --execute='{cmd}'",
    )
    my_container.exec_docker()

    logging.info("mySQL command DONE")


if __name__ == "__main__":
    import sys
    import argparse

    run_id = random.randrange(100_000)

    logging.basicConfig(level=logging.INFO, format=f'%(asctime)s:{CONST.script_name}:ID{run_id}:%(levelname)s: %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')

    parser = argparse.ArgumentParser(description="Manage Trax Database", add_help=False)
    parser.add_argument(
        "-h", "--help", action=utils._HelpAction, help="show this help message and exit"
    )
    create_parsers = parser.add_subparsers(help="sub-command help")

    # create the parser for the "create" command
    parser_create = create_parsers.add_parser("create", help="create help")
    parser_create.set_defaults(command="create")
    parser_create.add_argument("-d", "--db", help="Database to create", required=True)
    parser_create.add_argument("-e", "--env", required=True, help="Path to the .env file")

    # create the parser for the "remove" command
    parser_remove = create_parsers.add_parser("remove", help="remove help")
    parser_remove.set_defaults(command="remove")
    parser_remove.add_argument("-d", "--db", help="Database to remove", required=True)
    parser_remove.add_argument("-e", "--env", required=True, help="Path to the .env file")

    # create the parser for the "list" command
    parser_list = create_parsers.add_parser("list", help="list help")
    parser_list.set_defaults(command="list")
    parser_list.add_argument("-e", "--env", required=True, help="Path to the .env file")

    parser_populate = create_parsers.add_parser("populate", help="populate help")
    parser_populate.set_defaults(command="populate")
    parser_populate.add_argument("-d", "--db", help="Database to remove", required=True)
    parser_populate.add_argument(
        "-j", "--json", help="Json file to add in database", required=True
    )
    parser_populate.add_argument("-e", "--env", required=True, help="Path to the .env file")

    # If no argument provided, print --help
    if len(sys.argv) == 1:
        parser.print_help(sys.stdout)
        sys.exit(0)

    args = parser.parse_args()

    # Check if only 1 command is used
    sum_commands = (
            int("create" in sys.argv)
            + int("populate" in sys.argv)
            + int("list" in sys.argv)
            + int("remove" in sys.argv)
            )
    if sum_commands > 1:
        error("Use only one command between create, remove, populate or list")
    if sum_commands == 0:
        error("Use one command between create, remove, populate or list")

    # Read the env file
    env = env.Env(args.env)

    # use getattr to check if value is available in the namespace args.
    # When using subparser like the 'list' one, json or db are not set and raise a Namespace error
    # getattr use a None value by default if element is not set
    CASES = {
            "create": (execute_mysql_cmd, [f"CREATE DATABASE {getattr(args, 'db', None)}"]),
            "remove": (execute_mysql_cmd, [f"DROP DATABASE {getattr(args, 'db', None)}"]),
            "list": (execute_mysql_cmd, ["SHOW DATABASES"]),
            "populate": (populate_db, [getattr(args, 'db', None), getattr(args, 'json', None)]),
    }

    # The first element in the function name, then it's argument
    fct, args = CASES[args.command]
    fct(env, *args)

    exit(0)
